// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function ConnectToDB(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:string,arg7:number):Promise<void>;

export function Greet(arg1:string):Promise<string>;

export function Test(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string):Promise<void>;

export function WriteToDB(arg1:Array<models.Pair>):Promise<void>;
