// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ConnectToDB(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['ConnectToDB'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function Test(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['Test'](arg1, arg2, arg3, arg4, arg5);
}

export function WriteToDB() {
  return window['go']['main']['App']['WriteToDB']();
}
